name: CI
on:
  push:
    branches: [ main ]
jobs:
  build:
    concurrency: ci-dev
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: write
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: 20
    - run: npm ci
    - run: npx playwright install --with-deps
    - uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
        aws-region: us-east-1
    - uses: serverless/github-action@v3.2
      with:
        args: deploy --stage dev
    - run: npm run build:dev
    - uses: serverless/github-action@v3.2
      with:
        args: s3sync --stage dev
    - run: npm run test:unit && npm run test:e2e
      env:
        THUMBSHOT_TEST_USER_PASSWORD: ${{ secrets.THUMBSHOT_TEST_USER_PASSWORD }}
        THUMBSHOT_PRO_TEST_USER_PASSWORD: ${{ secrets.THUMBSHOT_PRO_TEST_USER_PASSWORD }}
        THUMBSHOT_PRO_TEST_USER_PASSWORD_2: ${{ secrets.THUMBSHOT_PRO_TEST_USER_PASSWORD_2 }}
    - uses: actions/upload-artifact@v4
      if: always()
      with:
        name: playwright-report
        path: playwright-report/
        retention-days: 7
  deploy:
    concurrency: ci-prod
    needs: build
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: write
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: 20
    - run: npm ci
    - uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
        aws-region: us-east-1
    - uses: serverless/github-action@v3.2
      with:
        args: deploy --stage prod
    - run: npm run build
    - uses: serverless/github-action@v3.2
      with:
        args: s3sync --stage prod